// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9SGRa6R9GlymyypI8k-PyQcpPXRbe4zU',
    appId: '1:377548524163:web:546b0bd6ea1b037b41a9b6',
    messagingSenderId: '377548524163',
    projectId: 'fec-school-notifications',
    authDomain: 'fec-school-notifications.firebaseapp.com',
    storageBucket: 'fec-school-notifications.appspot.com',
    measurementId: 'G-Y36BR82RJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTUo5tAP4GI_eQ1Ao-jxZ6Junm3A6R_0',
    appId: '1:377548524163:android:a720beff513d59eb41a9b6',
    messagingSenderId: '377548524163',
    projectId: 'fec-school-notifications',
    storageBucket: 'fec-school-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKh1ef1o9DUMQH1-LQsFj0W-y1mcozrdk',
    appId: '1:377548524163:ios:cad4eff1d176f48b41a9b6',
    messagingSenderId: '377548524163',
    projectId: 'fec-school-notifications',
    storageBucket: 'fec-school-notifications.appspot.com',
    iosBundleId: 'com.example.fecApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKh1ef1o9DUMQH1-LQsFj0W-y1mcozrdk',
    appId: '1:377548524163:ios:b8b5bf96d616f6f741a9b6',
    messagingSenderId: '377548524163',
    projectId: 'fec-school-notifications',
    storageBucket: 'fec-school-notifications.appspot.com',
    iosBundleId: 'com.example.fecApp2.RunnerTests',
  );
}
